### ISSUE TITLE
Move installer menus from mne-feedstock to this repo

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-installers#100]
Once https://github.com/conda/constructor/pull/500 has been merged, we **may** be able to get rid of the `mne-installer-menus` conda-forge package and instead move all the menu-related files to this repo and simply configure the installer to place those files in the correct location before `menuinst` is being run. This would allow us to test & release changes to the menus without tagging a new `mne-base`, `mne`, and `mne-installer-menus` release everytime!

**Comment by larsoner** [comment]
@hoechenberger do you want to give this a try now?

**Comment by hoechenberger** [comment]
Let's not touch this for now and instead wait until we can completely abandon the napari forks we currently use to build our installers. Once we're back in vanilla, we can start looking into this issue here again. Agreed?

**Comment by larsoner** [comment]
Yeah that makes sense!

**Comment by larsoner** [comment]
@hoechenberger it would be good to tackle this once #195 lands. Do you know the changes that need to be made or can you point me to an example? I could look into this next

**Comment by larsoner** [comment]
I guess it would mean just moving `mne-feedstock/recipe/menu` to `mne-installers/assets/menu`, renaming `menu/menu.json` to `menu/mne.json` (I think?) then adding `menu/*` to `extra_files` config value. But this requires `menuinst` to be run *after* the `extra_files` are copied. I guess it's worth a shot...

**Comment by hoechenberger** [comment]
Yes I totally lost track of when menuinst is now running :(

**Comment by larsoner** [comment]
Based on how `menu_packages` config var works I think we're using things the intended way so I'll close. But @hoechenberger if you think it is possible to move to the recipe let's reopen
