### ISSUE TITLE
Test M1 installers before making a public release

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-installers#128]
https://github.com/mne-tools/mne-installers/releases/tag/untagged-41d19bf875fbbe3e2fab

**Comment by hoechenberger** [comment]
The installer title says it's version 1.0.3_0, but it should be 1.0.3_1 🤔 

<img width="732" alt="Screen Shot 2022-06-03 at 12 53 14" src="https://user-images.githubusercontent.com/2046265/171840644-2aeda1a8-1411-419b-a02c-96d729d8de1b.png">

**Comment by hoechenberger** [comment]
Looking good so far:
```shell
❯ mne sys_info
Platform:         macOS-12.4-arm64-arm-64bit
Python:           3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:42:03) [Clang 12.0.1 ]
Executable:       /Applications/MNE-Python/.mne-python/bin/python3.10
CPU:              arm: 8 cores
Memory:           16.0 GB

mne:              1.0.3
numpy:            1.21.6 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:            1.8.1
matplotlib:       3.5.2 {backend=MacOSX}

sklearn:          1.1.1
numba:            0.55.1
nibabel:          3.2.2
nilearn:          0.9.1
dipy:             1.5.0
cupy:             Not found
pandas:           1.4.2
pyvista:          0.34.0 {OpenGL 4.1 Metal - 76.3 via Apple M1}
pyvistaqt:        0.9.0
ipyvtklink:       0.2.2
vtk:              9.1.0
PyQt5:            5.15.4
ipympl:           0.9.1
pooch:            v1.6.0

mne_bids:         0.10
mne_nirs:         0.2.1
mne_features:     0.2
mne_qt_browser:   0.3.1
mne_connectivity: 0.3
```

**Comment by hoechenberger** [comment]
Spyder is working too

<img width="1552" alt="Screen Shot 2022-06-03 at 13 11 37" src="https://user-images.githubusercontent.com/2046265/171843104-1d051c3b-f2e7-4bce-98a5-1fa2f53fe583.png">

**Comment by hoechenberger** [comment]
3D viz works:

<img width="1201" alt="Screen Shot 2022-06-03 at 13 13 59" src="https://user-images.githubusercontent.com/2046265/171843453-ac1e8424-3f44-47b6-9c83-8c47af064985.png">

**Comment by larsoner** [comment]
Awesome, sounds like we're good to go, then, right?

**Comment by hoechenberger** [comment]
@larsoner We still need #129 or at least the part of it that bumps the build number

Then force-delete the 1.0.3-post1 tag I created

Then make a new draft release again

and then we can publish it :)

**Comment by hoechenberger** [comment]
As per discussion on Discord, we're holding off the new release until we have MNE 1.1, to not compromise the "wow" effect of the new native builds :) so the idea is to announce 1.1 together with the M1 builds.

**Comment by larsoner** [comment]
I think we've tested these so I'll close. I'll cut a prerelease and we should test on every platform anyway
