### ISSUE TITLE
Run mne sys_info in post-install script?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-installers#132]
The first run of mne sys_info (or, actually, just the first import of MNE and some of its dependencies) seem to take a long time on my machine (macOS). Subsequent runs are usually **much** faster. This seems to have to do with some library caching / checking / integrity analysis or whatever macOS is performing.

I think if we were to execute `mne sys_info` as part of the installer (very last step), we could probably speed up the first start of the freshly-installed package, hence improve the user experience.

WDYT?

**Comment by larsoner** [comment]
We have had issues in the past with this crashing, which makes me a little bit wary of doing it. But if we can run it and ignore the return value (e.g., getting a bad one from a segfault) then I agree it would be nice!

**Comment by hoechenberger** [comment]
You mean the crashes due to issues with 3D / PyVista?

**Comment by larsoner** [comment]
In bash you can `set +e` then run the command then `set -e`, but it's easier just to `command || true`

**Comment by larsoner** [comment]
Fixed by #133
