### ISSUE TITLE
ENH: Speed up build+test

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-installers#134]
Why do we build installers for two versions of each OS (plus M1)? It seems like we should build just on the oldest one for each OS (plus M1), then test on the oldest and the newest version of each OS (plus M1). In other words, it seems like we should have two stages: the first "build" stage on 4 OSes (old ubuntu/mac/win + M1), and a second "test" stage on 7 OSes (old/new x ubuntu/mac/win, plus M1).

**Comment by hoechenberger** [comment]
I like this idea! Let's do this! 


… who'll do it? ;)

**Comment by hoechenberger** [comment]
Please do go ahead if you have the time, my todo bucket is overflowing already…

**Comment by larsoner** [comment]
Looks like a combo of these two docs should suffice:

- https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
- https://levelup.gitconnected.com/github-actions-how-to-share-data-between-jobs-fc1547defc3e

After #133 is in I'll give it a shot. One disadvantage is that these are ~1GB so it'll actually add some time to download them. But given that most of our failures are in the build stage and that stage takes ~20 minutes, it'll probably still be a net win time-wise. Plus then we can download the artifacts as part of the PR if we want.

I'm not sure at what point these sizes will create problems, though, since for every successful build/commit we'll have ~4GB of artifacts created...
