### ISSUE TITLE
Set MPLBACKEND env var to enforce using Qt5Agg backend?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-installers#140]
Would there be any drawbacks on headless machines, e.g. running through Jupyter Lab? Would Matplotlib just refuse to work there, instead of automatically picking a different backend?

Came up in https://mne.discourse.group/t/semi-interactive-plot-with-matplotlib-backend/5094

**Comment by hoechenberger** [comment]
The MPL docs say:

> The first usable backend in the following list is selected: MacOSX, QtAgg, GTK4Agg, Gtk3Agg, TkAgg, WxAgg, Agg. 
https://matplotlib.org/stable/users/explain/backends.html#selecting-a-backend

So maybe it's sufficient to only set this env var on macOS, to exclude potential side effects on all other platforms.

**Comment by cbrnr** [comment]
For the installers this should be OK. Please don't do that for MNE-Python in general though, because having `macosx` as the default on macOS allows users to produce plots without having to install PyQt/PySide.

**Comment by hoechenberger** [comment]
Yes this is really limited to the installers.
