### ISSUE TITLE
Pin ipywidgets to <8

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-installers#156]
Otherwise, tqdm may not work properly in VS Code:
https://github.com/microsoft/vscode-jupyter/issues/8552#issuecomment-1263940999

**Comment by alex180500** [comment]
also tqdm doesn't work for python 3.11

**Comment by hoechenberger** [comment]
We don't currently ship Python 3.11, as a number of MNE's dependencies are not quite ready for 3.11 yet :)
