### ISSUE TITLE
ENH: Add mne-bids-pipeline

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-installers#159]
Once we have a proper PyPI and conda-forge release, can we close this and make a PR to mne-docker to add it there? It would be nice to keep mne-installers and mne-docker in sync. Even better if mne-docker could use mne-installers to do this...

_Originally posted by @larsoner in https://github.com/mne-tools/mne-bids-pipeline/issues/594#issuecomment-1320918568_

**Comment by hoechenberger** [comment]
Closed via #158
