### ISSUE TITLE
BUG: Windows installers with "install for everyone" not vetted

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-installers#182]
I was helping someone who used a windows installer and clicked the "Install for everyone" checkbox or whatever it is on Windows. When they opened the MNE command prompt, at the top it said "Access is denied". If they run the prompt as admin, this does not happen.

There are possibly other things like this. At some point we should locally test that at least this is fixed.

**Comment by larsoner** [comment]
... and this is probably the cause of https://mne.discourse.group/t/mne-not-loading-in-spyder/6720 as well.

@hoechenberger another easier option (than changing permissions as discussed on Discourse) is to disallow system-wide installs for Windows. `chown -R <user> <install path>` will make things work *for one user* but then could keep things broken for any other system users (their use of Numba could freeze instead!), and `chmod a+w` or so could fix it but it seems like a pretty insecure choice (all users can modify the install for all other users). So if we can just disable system-wide installs it seems safest and easiest to me.

**Comment by hoechenberger** [comment]
We need to escalate this to the constructor repo

I like the proposal

**Comment by larsoner** [comment]
Okay I tried in https://github.com/conda/constructor/issues/662

**Comment by larsoner** [comment]
Sounds like the fix there isn't trivial. My vote for now is to `chown -R` the files on Windows so that at least the user who installed them all has permissions to modify them. It seems better than a `chmod a+w` or so. @hoechenberger agreed?

**Comment by hoechenberger** [comment]
Let's see if we can somehow disable system-wide install altogether.

Also we should file a bug with Numba, because – well, it's clearly a bug on their end, right?

**Comment by larsoner** [comment]
Could be theirs, could be something is weird with the conda package permissions, could be the installer does something wrong with the package permissions. I haven't isolated it nicely enough to definitively bother the right people yet

**Comment by hoechenberger** [comment]
We could set this environment variable:

https://numba.pydata.org/numba-doc/dev/reference/envvars.html#envvar-NUMBA_CACHE_DIR

**Comment by larsoner** [comment]
That would be a good start as it would at least allow `import mne` to work, so +1 on doing that.

But there are other issues with sys-wide installs like people not being able to `conda install` without an elevated prompt that we might still want to strongly discourage, so I think we'll still want to disable or at least discourage system-wide installs for most people
