### ISSUE TITLE
Installer hangs on macOS

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-installers#191]
I just tried the installer on macOS (version 11.7.8, which is not the latest version, but the last supported version for my old Mac). Unfortunately, the installer hangs in the "Running package scripts" step. I can't even cancel, only force quitting closes the installer (but of course not gracefully).

**Comment by hoechenberger** [comment]
Are you sure it hangs and is not just taking awfully long to finish? You can access the installer logs through some menu, too

**Comment by cbrnr** [comment]
Yeah, it did finally finish after almost 10 minutes. I didn't expect it to take so long, especially since the message had an ETA of 2 minutes.

**Comment by hoechenberger** [comment]
Yes the ETA is not correct

The actual
Install takes place when it says this but about running package scripts
