### ISSUE TITLE
MAINT: Migrate to standard version control procedures

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-installers#209]
It's a bit weird to me to have `recipes/mne_python_*.*/` rather than a single `recipes/mne_python/`.

- Most old recipes very well might not work anymore.
- I don't think we'll ever really support multiple versions simultaneously, but even if we do it seems more standard to do this with branches (like `maint/1.5` and `maint/1.6`) than it does with folders.
- Having multiple versions ruins our `git blame` for lines (for example [our latest construct.yaml](https://github.com/mne-tools/mne-installers/blame/main/recipes/mne-python_1.5/construct.yaml) only has changes going back ~3mo even though some lines are effectively much older)

@hoechenberger if you agree with migrating to a more standard version control scheme under a single `recipes/mne_python/`, we could try to migrate gracefully by merging backward (rename 0.23 to root `mne_python`, then merge 0.24 into `mne_python`, then 0.25 into 0.23, etc. in single PRs). That way we at least get to see what was changed in each version release. (I'll get all `git blame` in terms of authorship but at least it'll be clearer when stuff was changed.)

**Comment by hoechenberger** [comment]
@larsoner I'm also happy with just declaring the latest recipe "the" recipe and deleting the old ones, to make things easier… in any case, +1 to having only a single recipe.
