### ISSUE TITLE
BUG: macOS certificates broken

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-installers#232]
@hoechenberger in case you didn't see the top comment from https://github.com/mne-tools/mne-installers/pull/230#issue-2004552478 , the macOS certs have an issue that will make it so we can't release:

https://github.com/mne-tools/mne-installers/actions/runs/6946567994/job/18898366624

**Comment by hoechenberger** [comment]
Seems to be related to a newer OpenSSL on the CI machine than what we had in the past

I can try to look into this tonight, maybe I need to re-export the certs or something
