### ISSUE TITLE
Make artifacts available without tagging a new release (e.g., for testing)

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-installers#30]
Currently, the GH Actions artifacts are only exposed & downloadable if the `Release` step of your `build` action is run. This step will only run if there's a new tag on `main`, and will create a new release draft with the artifacts attached.

For interactive testing, obviously, this isn't the best approach.

It appears I'd [experimented](https://github.com/hoechenberger/mne-installers/blob/d7b7e5d5fda6950d06e2ffd31970bcc94c7ba63c/.github/workflows/build.yml#L91-L97) with temporary artifact storage and [removal](https://github.com/hoechenberger/mne-installers/blob/d7b7e5d5fda6950d06e2ffd31970bcc94c7ba63c/.github/workflows/purge_artifacts.yml) before, but for reasons I don't remember anymore, I disabled the respective activities. (Maybe we ran into storage limitations or something? I really don't remember)

If anyone's familiar with ephemeral GH Actions artifact storage (@larsoner perhaps?), any help here would be greatly appreciated.

**Comment by larsoner** [comment]
I haven't worked with GH Actions artifacts at all so I have no idea :(

However, @agramfort mentioned that some repo builds their website with GH actions (I think on PRs) + artifacts, and then just exposes them interactively via CircleCI by having it download then re-expose them. So it seems like it should be possible to have GH actions artifacts be exposed on PRs...

**Comment by agramfort** [comment]
this one https://github.com/braindecode/braindecode

**Comment by larsoner** [comment]
I have recently used and tested an artifact without making a release. It shows up in the Actions for the given run when you look at the Summary page IIRC. It disappears quickly (overnight?) but I think that's okay
