### ISSUE TITLE
Transfer to mne-tools

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-installers#49]
It seems like this repo should live in `mne-tools`. One disadvantage is that we'll have to share CI resources, but hopefully once things work properly here, we'll only need to update things at release time, so I think CI sharing will be okay.

@hoechenberger let me know when it's a good time to transfer this repo to the mne-tools org. I'm thinking after the installers are 100% ready to go, and we're about to release, i.e., sometime this week (assuming everything works by then!).

**Comment by hoechenberger** [comment]
Sounds great.

But even so, I see room for reducing CI resource usage. For example, upon pushing a tag / creating a release, we can skip the CI runs that don't actually produce a release artifact (that's in fact half of the runs!)

Also we could make use of some "control keywords" (via the commit message, as we do usually?) to explicitly skip or only run select jobs.

Lastly, pushing a new commit to a PR branch that currently has running CI jobs doesn't cancel those jobs, but it should. (For the moment, I kill them manually via the Actions pane)

If you feel bored and want to look into any of these points, feel free to do so :)
