### ISSUE TITLE
Add MNELAB (requires Qt 6)

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-installers#82]
As soon as we have Qt6 on `conda-forge`

To keep track: https://github.com/conda-forge/qt-main-feedstock/pull/14

**Comment by cbrnr** [comment]
Yes, I saw that. 🤷‍♂️? It can be installed with pip, even in a conda env. I don't know why it is necessary to create conda packages when this is so much effort and when official binaries exist on PyPI.

**Comment by hoechenberger** [comment]
Because the installer ships much more than just Python packages

**Comment by cbrnr** [comment]
Yeah, it's a pity the installer can't include pip packages.

**Comment by hoechenberger** [comment]
We can ship custom files, so we could include packages and install them via a post-install script, but it would require some fiddling.

**Comment by hoechenberger** [comment]
> I think it would be worth a try. Maybe we can pip install in the post-install script?

Yes. It's trivial to just run `pip install` in the post-install script, or to include a desktop shortcut / `.app` that opens a shell and does that thing automatically.

The problem with this is that it would require network / internet access.

To avoid this, we'd need to bundle all PyPI dependencies, drop them into a separate folder, and run something like 

```shell
pip install --index-url /path/to/pypi-packages ...
```
To ease things, we could simply bundle all "pip requirements" in a .zip file that we include in the installer.

I'm **still** reluctant to do so as I believe the last time I tried to get PyQt6 working with my MNE conda environment, things got all sorts of "twisted-up" and I ran into some issues. I don't remember details though.

**Comment by hoechenberger** [comment]
Another approach:
Re-bundle the "pip requirements" as `conda` packages. We won't be able to publish those on `conda-forge`, but we could upload them to a custom `mne` channel on anaconda.org and list this package source in our `construct.yaml`. Then we won't have to fiddle with any post-install magic.

https://docs.conda.io/projects/conda-build/en/latest/user-guide/wheel-files.html#building-a-conda-package-from-a-wheel-file

**Comment by cbrnr** [comment]
I can do that. The dependencies that are not available on conda-forge are `PySide6`, which itself requires `PySide6-Addons`, `PySide6-Essentials`, and `shiboken6`. That's it.

**Comment by hoechenberger** [comment]
Qt6 and PySide6 are now part of `conda-forge` (PySide6 is being built as we speak)

Once it's landed for all platforms, we can try to revive the MNELAB feedstock.

See https://anaconda.org/conda-forge/pyside6

**Comment by cbrnr** [comment]
Meanwhile, there is another problem that needs to be fixed first. Matplotlib doesn't work with the PySide6 backend, which MNELAB requires. They have already fixed it (https://github.com/matplotlib/matplotlib/pull/24158), but we are waiting for a new release. Therefore, it's maybe best to wait for Matplotlib v3.6.2.
