### ISSUE TITLE
Uninstaller?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-installers#89]
I finally tried the Linux installer. It only took a couple of minutes and had a nice progress bar. Nice!

Is there some process for uninstallation? Maybe we should have an icon for it on Linux, or at least if you re-run the installer it should have an option for removal?

**Comment by hoechenberger** [comment]
Currently there's only an uninstaller for Windows. If we want one for other platforms, we'd have to cook up our own. I'm more inclined to document the manual uninstall procedure so we don't end up screwing up our users' systems if we have a stupid bug in our uninstall routine 😅 Let's talk about this during the office hour later today!

**Comment by larsoner** [comment]
Sure, manual doc would be fine. We can just add a link from the current installation page saying what to do on each platform. For macOS it would be just this drag, on Windows it would be to use the uninstall link, for Linux it's to delete the directory plus some .desktop file(s) somewhere
