### ISSUE TITLE
Dealing with the mne-python conda environment folder on macOS

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-installers#96]
Currently, we dump the conda environment into /Applications/MNE-Python, right next to the `.app` bundles we create.

My long-term goal is to only deploy a **single** `MNE-Python.app` that contains the entire conda env, and when opened, displays a launcher with shortcuts to Spyder, our website, etc

Until then, I'd like to "hide" the conda environment folder. I was thinking of just renaming it to `.mne-python` so it wouldn't show up in the Finder and Spotlight by default.

Any thoughts on this, @larsoner?

**Comment by larsoner** [comment]
The launcher idea is what Anaconda does. I think it's workable, but it *is* pretty nice to have an immediate shortcut to Spyder (as an app) for example. As long as people can pin this to their dock, though, it's probably not a big issue

**Comment by hoechenberger** [comment]
Good point about being able to e.g. have Spyder in your Dock.

WDYT about my idea of "hiding" the conda environment folder by prepending a `.`?

**Comment by larsoner** [comment]
Sounds good if it works! I do like the idea of hiding it somehow, as it seems a bit out of place.

Another option would be to put the actual Python bits in `~/mne-python/...` as done on Windows and Linux, and then just have `~/Applications/` (or `/Applications/`) have the `MNE-Python` folder with `.app`s in it

**Comment by larsoner** [comment]
... it does appear to work -- I did `mv mne-python_1.0.0_0 .mne-python_1.0.0_0` and it no longer shows up in the dock, which is much better!

<img width="507" alt="Screen Shot 2022-03-19 at 2 23 56 PM" src="https://user-images.githubusercontent.com/2365790/159133789-68c379ae-9763-44e5-bf9f-263baefd1a97.png">

**Comment by hoechenberger** [comment]
> Another option would be to put the actual Python bits in `~/mne-python/...` as done on Windows and Linux, and then just have `~/Applications/` (or `/Applications/`) have the `MNE-Python` folder with `.app`s in it

I'm not in favor, as that's not the macOS way to do it.

There's basically two "right" ways:

Either one stores this stuff in `~/Library/Application Support`, or in the `.app` bundle's `Resources` folder (which ons is preferred depends on the use case; in our situation, the `.app` bundle would probably be the better choice)

Currently, we're doing neither of them; however, at least the conda env is stored inside the `MNE-Python` folder in `/Applications`, so if a user deletes the `MNE-Python` folder, the huge conda environment will be gone too (good!)

**Comment by hoechenberger** [comment]
> ... it does appear to work -- I did `mv mne-python_1.0.0_0 .mne-python_1.0.0_0` and it no longer shows up in the dock, which is much better!

Nice! Let's try this one then
